### PR TITLE
Fix a crash bug

### PR DESCRIPTION
**Pull request by kmecpp**

### CODE REVIEW

**Comment by KingLemming** [comment]
So the thing is, if this logic ever causes a crash bug, your world has been corrupted somehow. Invalid metadata isn't normally possible.

**Comment by kmecpp** [comment]
It happened with a Bukkit plugin I was using and it also happens on a Bungeecord when switching between servers

**Comment by KingLemming** [comment]
Yeah, and those are abnormal situations. Modded MC requires clients and servers to match IDs. In 1.10+ this is handled very elegantly. Forge in fact handles this fairly elegantly in 1.7.10 alone, but apparently Bukkit and Bungeecord mess that up.

**Comment by kmecpp** [comment]
Well is there any downside to merging the PR? It has zero effect on normal behavior and It fixes issues in abnormal situations. Those situations shouldn't happen but they can and they're common with Bungeecord.

**Comment by KingLemming** [comment]
Potentially yes there is. A "fix" like this means that you are accepting world corruption / data mismatch and almost certainly something else is going to go wrong too.

**Comment by kmecpp** [comment]
You're not accepting world corruption/data mismatch, you're just not intentionally crashing the entire game if something goes slightly wrong. Doing that just makes the whole thing 100x harder to debug and fix if there is a real issue. If a player visually sees a block is broken somehow if the metadata gets corrupted they can easily report that and it makes it so much easier to bug test and try and replicate. If the game crashes then no one can even go near the corrupt block in the game and the easiest solution at that point is to just delete the entire world file that contains it which is not a fun thing if its in your base.

Most other mods have this check in place. I don't know why the Bukkit plugin was causing this to occur but the issue only occurred with Thermal Foundation ores. Also this is completely normal behavior for BungeeCord when switching between two modded servers. Most of the time if this occurs its not a serious issue so I don't see the point in letting the game crash when it can easily be avoided. If another issue occurs because of this then so what? You still avoided the vast majority potential game crashes

**Pull request merged**
