### PR TITLE
Update de_DE.lang

### PR DESCRIPTION
**Pull request by ReneMuetti**
Update Translation

### CODE REVIEW

**Comment by KingLemming** [comment]
You're renaming Nickel, Platinum, and Mana Infused to incorrect translations. I can't accept this as is.

**Comment by ReneMuetti** [comment]
hello
Please help me in understanding

The Item is handled internally as nickel. But the name is Ferrous (iron - containing). According TFB-Wiki, the ore is a source of nickel. Wikipedia certifies both metals differences. I am therefore (apparently falsely) vin Nickel assumed. I know, therefore, not directly as it is to understand.

Also the Item Platinum is indeed known by name as, but is given as a name Shiny. Is it platinum or just a "shiny metal")

According to the internal designation Mithril (from the Roman world JRT) it is a metal which is harder than steel and lighter than silk. It is named "Mana Infused". Is this a derivative Description of product or dependence?

I want no case "criticize" - I just want to understand. Finally, I must often explain in my TS exactly why and how that is now exactly and not just different.

Thank you for your reply

**Comment by Tora-B** [comment]
The ores are intended to be the same as nickel, platinum, and mithril for the purpose of other mods which use those metals. However, the names are too modern-sounding for the setting of Minecraft, as KingLemming perceives it. So instead he gave them names that describe them, rather than define them. In the documentation on [teamcofh.com], it says "The reason the metal is not called Nickel is because it is not part of the [seven metals of antiquity](https://en.wikipedia.org/wiki/Metals_of_antiquity). Steve? doesn't know what to call the metal, resulting in the less 'logical' name Ferrous Metal.", and much the same for Shiny.

Note that Invar is a real alloy, composed of iron and nickel. Nickel is frequently found in combination with iron, and thus the ore is "ferrous" -- it's not iron, but contains iron. Pulverizing iron ore also has a chance to give you some ferrous dust as well.

Platinum is a similar in appearance to silver, except lighter in color, and highly resistant to corrosion. Thus, it stays "shiny", while silver tarnishes easily.

Mana Infused Metal is a magical metal, like Mithril, but has few properties other than that at present. It doesn't naturally appear in the world, and there's no way to make it with anything that is normally obtainable. However, if you put down some Primal Mana (using creative mode), it will turn any silver ore or blocks it touches into Mana Infused Metal. Thus, it describes the process of creating it, inasmuch as it can be created at the moment.

**Comment by ReneMuetti** [comment]
hmm ...
I'll think about it tonight, as the best solution. I'll adjust the translations accordingly then.

**Pull request closed without merging**
